apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops 
              image: kacperadamiak/lab10zad2gitops
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/Kacper-adamiak/lab10_zad2_config /tmp/lab10_zad2_config && find /tmp/lab10_zad2_config -name '*.yaml' -exec kubectl apply -f {} \;
